#!/usr/bin/env ruby
# ---------------------------------------------------------------
# File          : whichruby.rb
# Authors       : Aoran Zeng <ccmywish@qq.com>
# Created on    : <2022-05-06>
# Last modified : <2023-05-19>
#
# whichruby:
#
#   Test which ruby is called using this gem and where am I.
# ---------------------------------------------------------------

puts "[ Invoked at: #$0 ]
#{RUBY_DESCRIPTION}"

# Make it last, because we wanna feed ruby.exe path to some program
puts RbConfig.ruby
