#!/usr/bin/env ruby
# ---------------------------------------------------------------
# File          : wrb.rb
# Authors       : Aoran Zeng <ccmywish@qq.com>
# Created on    : <2022-05-07>
# Last modified : <2023-05-19>
#
# wrb:
#
#   Another name for `whichruby`
# ---------------------------------------------------------------

puts "[ Invoked at: #$0 ]
#{RUBY_DESCRIPTION}"

# Make it last, because we wanna feed ruby.exe path to some program
puts RbConfig.ruby
