#!/usr/bin/env ruby
# ---------------------------------------------------------------
# File          : wrb.rb
# Authors       : ccmywish <ccmywish@qq.com>
# Created on    : <2022-05-07>
# Last modified : <2022-05-07>
#
# wrb:
#
#   Another name for `whichruby`
#
# ---------------------------------------------------------------

puts "[ in #$0 ]
#{RUBY_DESCRIPTION}"
